/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import static UI.SearchItem.getBufferedImageFromJson;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Base64;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.json.JSONObject;

/**
 *
 * @author Admin
 */
public class BuildItem extends javax.swing.JPanel {
    private JSONObject device;
    private Home parent;
    /**
     * Creates new form BuildItem
     */
    public static BufferedImage getBufferedImageFromJson(JSONObject jsonObject, String key) throws IOException {
        if (!jsonObject.has(key)) {
            throw new IllegalArgumentException("Key not found in JSONObject: " + key);
        }

        String base64Image = jsonObject.getString(key); // Get string Base64 from JSON
        byte[] imageBytes = Base64.getDecoder().decode(base64Image); // Decode Base64

        // Change into BufferedImage
        try (ByteArrayInputStream bis = new ByteArrayInputStream(imageBytes)) {
            return ImageIO.read(bis);
        }
    }
    
    public BuildItem(Home parent, JSONObject data) {
        initComponents();
        device = data;
        Type.setText(data.getString("type"));
        Brand.setText(data.getString("brand"));
        DeviceButton.setText(data.getString("name"));
        try {
            BufferedImage originalImage = getBufferedImageFromJson(data, "icon");
            BufferedImage resizedImage = new BufferedImage(75, 75, originalImage.getType());
            Graphics2D g2d = resizedImage.createGraphics();
            g2d.drawImage(originalImage, 0, 0, 75, 75, null);
            g2d.dispose();
            ImageIcon originalIcon = new ImageIcon(resizedImage);

            Image scaledImage = originalIcon.getImage().getScaledInstance(75, 75, Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            JLabel imageLabel = new JLabel(scaledIcon);
            imageLabel.setBounds(0, 0, 75, 75);
            
            Icon.add(imageLabel);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon = new javax.swing.JPanel();
        DeviceButton = new javax.swing.JButton();
        Type = new javax.swing.JLabel();
        Brand = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(32767, 100));
        setMinimumSize(new java.awt.Dimension(0, 100));
        setPreferredSize(new java.awt.Dimension(250, 100));

        Icon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout IconLayout = new javax.swing.GroupLayout(Icon);
        Icon.setLayout(IconLayout);
        IconLayout.setHorizontalGroup(
            IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        IconLayout.setVerticalGroup(
            IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        DeviceButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        DeviceButton.setForeground(new java.awt.Color(51, 0, 153));
        DeviceButton.setText("Device");
        DeviceButton.setBorder(null);
        DeviceButton.setBorderPainted(false);
        DeviceButton.setContentAreaFilled(false);
        DeviceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeviceButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        DeviceButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        DeviceButton.setMargin(new java.awt.Insets(2, 5, 3, 5));
        DeviceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeviceButtonActionPerformed(evt);
            }
        });

        Type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Type.setText("Type");

        Brand.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Brand.setText("Brand");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeviceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Type)
                            .addComponent(Brand))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeviceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Type)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Brand)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void purchase() {
        parent.purchase(device);
    }
    
    private void DeviceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeviceButtonActionPerformed
        // TODO add your handling code here:
        DeviceInformation newInfo = new DeviceInformation(parent, device);
        newInfo.setLocationRelativeTo(null);
        newInfo.setVisible(true);
    }//GEN-LAST:event_DeviceButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Brand;
    private javax.swing.JButton DeviceButton;
    private javax.swing.JPanel Icon;
    private javax.swing.JLabel Type;
    // End of variables declaration//GEN-END:variables
}
