/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Dimension;
import java.util.ArrayList;
import org.json.JSONObject;
import pc_builder.DeviceStorage;

/**
 *
 * @author Admin
 */
public class BuildedPC extends javax.swing.JPanel {
    private Home parent;
    /**
     * Creates new form BuildedPC
     */
    private ArrayList<String> devices;
    
    public BuildedPC(Home parent, int index, float price, ArrayList<String> devices) {
        this.devices = devices;
        initComponents();
        IndexLabel.setText(String.format("Build %d:",index));
        BuildPrice.setText(String.format("$%.2f", price));
        
        for (String id: devices) {
            JSONObject device = DeviceStorage.getItem(id);
            
            BuildItem newItem = new BuildItem(parent, device);
            newItem.setVisible(true);
            ItemContent.add(newItem);
        }
        
        ItemContent.setPreferredSize(new Dimension(400*devices.size(),150));
        ItemContent.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IndexLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ItemContent = new javax.swing.JPanel();
        BuildPrice = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 200));
        setMinimumSize(new java.awt.Dimension(0, 200));

        IndexLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IndexLabel.setText("Option 1");

        jScrollPane1.getHorizontalScrollBar().setUnitIncrement(10);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFocusable(false);

        ItemContent.setBackground(new java.awt.Color(214, 214, 214));
        ItemContent.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane1.setViewportView(ItemContent);

        BuildPrice.setBackground(new java.awt.Color(242, 242, 242));
        BuildPrice.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        BuildPrice.setForeground(new java.awt.Color(0, 153, 51));
        BuildPrice.setText("jButton1");
        BuildPrice.setBorderPainted(false);
        BuildPrice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuildPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BuildPrice.setOpaque(false);
        BuildPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IndexLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BuildPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndexLabel)
                    .addComponent(BuildPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuildPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuildPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuildPrice;
    private javax.swing.JLabel IndexLabel;
    private javax.swing.JPanel ItemContent;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
