/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Dialog;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;
import pc_builder.UserStorage;

/**
 *
 * @author Admin
 */
public class GetData extends javax.swing.JDialog {
    private BufferedImage originalImage;
    private BufferedImage resizedImage;
    private String targetKey;
    private ModifyData parent;
    private int mode = 0;
    /**
     * Creates new form Get
     */
    public GetData(ModifyData parent, String targetKey, String value) {
        super(parent, "Get Data", Dialog.ModalityType.APPLICATION_MODAL);
        this.parent = parent;
        this.targetKey = targetKey;
        initComponents();
        this.jTextArea.setText(value);
        try {
            originalImage = getBufferedImageFromJson(value);
            resize();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagePanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PathField1 = new javax.swing.JTextField();
        BrowseFile1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        WidthTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        HeightTextField1 = new javax.swing.JTextField();
        VIewFile2 = new javax.swing.JButton();
        VIewFile3 = new javax.swing.JButton();
        SaveAsJSON1 = new javax.swing.JCheckBox();
        OriginalSize1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        ImagePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PathField = new javax.swing.JTextField();
        BrowseFile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        WidthTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        HeightTextField = new javax.swing.JTextField();
        VIewFile = new javax.swing.JButton();
        VIewFile1 = new javax.swing.JButton();
        SaveAsJSON = new javax.swing.JCheckBox();
        OriginalSize = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        StringPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NumberPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        NumberField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        NumberType = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        Apply = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton_Image = new javax.swing.JButton();
        jButton_String = new javax.swing.JButton();
        jButton_Number = new javax.swing.JButton();

        jLabel5.setText("Path:");
        jLabel5.setPreferredSize(new java.awt.Dimension(30, 30));

        PathField1.setEditable(false);
        PathField1.setBackground(new java.awt.Color(254, 254, 254));

        BrowseFile1.setText("Browse");
        BrowseFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseFile1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Width:");
        jLabel6.setPreferredSize(new java.awt.Dimension(30, 30));

        WidthTextField1.setBackground(new java.awt.Color(254, 254, 254));
        WidthTextField1.setText("100");
        WidthTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WidthTextField1ActionPerformed(evt);
            }
        });
        WidthTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                WidthTextField1PropertyChange(evt);
            }
        });

        jLabel7.setText("Height:");
        jLabel7.setPreferredSize(new java.awt.Dimension(30, 30));

        HeightTextField1.setBackground(new java.awt.Color(254, 254, 254));
        HeightTextField1.setText("100");
        HeightTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                HeightTextField1PropertyChange(evt);
            }
        });

        VIewFile2.setText("View");
        VIewFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIewFile2ActionPerformed(evt);
            }
        });

        VIewFile3.setText("Export");
        VIewFile3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIewFile3ActionPerformed(evt);
            }
        });

        SaveAsJSON1.setText("Record as JSON");

        OriginalSize1.setText("Use Original Size");
        OriginalSize1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                OriginalSize1PropertyChange(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Image");

        javax.swing.GroupLayout ImagePanel1Layout = new javax.swing.GroupLayout(ImagePanel1);
        ImagePanel1.setLayout(ImagePanel1Layout);
        ImagePanel1Layout.setHorizontalGroup(
            ImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagePanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(ImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ImagePanel1Layout.createSequentialGroup()
                        .addGroup(ImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ImagePanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PathField1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ImagePanel1Layout.createSequentialGroup()
                                .addGroup(ImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(ImagePanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HeightTextField1))
                                    .addGroup(ImagePanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(WidthTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VIewFile2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BrowseFile1)
                            .addComponent(VIewFile3))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(ImagePanel1Layout.createSequentialGroup()
                        .addGroup(ImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaveAsJSON1)
                            .addComponent(OriginalSize1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ImagePanel1Layout.setVerticalGroup(
            ImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagePanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PathField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrowseFile1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ImagePanel1Layout.createSequentialGroup()
                        .addGroup(ImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WidthTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HeightTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveAsJSON1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OriginalSize1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ImagePanel1Layout.createSequentialGroup()
                        .addGroup(ImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VIewFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VIewFile3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(420, 350));

        Main.setLayout(null);

        jLabel1.setText("Path:");
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));

        PathField.setEditable(false);
        PathField.setBackground(new java.awt.Color(254, 254, 254));

        BrowseFile.setText("Browse");
        BrowseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseFileActionPerformed(evt);
            }
        });

        jLabel2.setText("Width:");
        jLabel2.setPreferredSize(new java.awt.Dimension(30, 30));

        WidthTextField.setBackground(new java.awt.Color(254, 254, 254));
        WidthTextField.setText("100");
        WidthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WidthTextFieldActionPerformed(evt);
            }
        });
        WidthTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                WidthTextFieldPropertyChange(evt);
            }
        });

        jLabel3.setText("Height:");
        jLabel3.setPreferredSize(new java.awt.Dimension(30, 30));

        HeightTextField.setBackground(new java.awt.Color(254, 254, 254));
        HeightTextField.setText("100");
        HeightTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                HeightTextFieldPropertyChange(evt);
            }
        });

        VIewFile.setText("View");
        VIewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIewFileActionPerformed(evt);
            }
        });

        VIewFile1.setText("Export");
        VIewFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIewFile1ActionPerformed(evt);
            }
        });

        SaveAsJSON.setText("Record as JSON");

        OriginalSize.setText("Use Original Size");
        OriginalSize.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                OriginalSizePropertyChange(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Image");

        javax.swing.GroupLayout ImagePanelLayout = new javax.swing.GroupLayout(ImagePanel);
        ImagePanel.setLayout(ImagePanelLayout);
        ImagePanelLayout.setHorizontalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ImagePanelLayout.createSequentialGroup()
                        .addGroup(ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ImagePanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PathField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ImagePanelLayout.createSequentialGroup()
                                .addGroup(ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(ImagePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HeightTextField))
                                    .addGroup(ImagePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(WidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VIewFile)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BrowseFile)
                            .addComponent(VIewFile1)))
                    .addComponent(SaveAsJSON)
                    .addComponent(OriginalSize))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ImagePanelLayout.setVerticalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagePanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrowseFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ImagePanelLayout.createSequentialGroup()
                        .addGroup(ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveAsJSON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OriginalSize)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ImagePanelLayout.createSequentialGroup()
                        .addGroup(ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VIewFile, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VIewFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        Main.add(ImagePanel);
        ImagePanel.setBounds(0, 10, 400, 210);

        StringPanel.setVisible(false);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("String");

        jButton1.setText("Finish");

        javax.swing.GroupLayout StringPanelLayout = new javax.swing.GroupLayout(StringPanel);
        StringPanel.setLayout(StringPanelLayout);
        StringPanelLayout.setHorizontalGroup(
            StringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StringPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StringPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        StringPanelLayout.setVerticalGroup(
            StringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StringPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Main.add(StringPanel);
        StringPanel.setBounds(0, 0, 400, 220);

        NumberPanel.setVisible(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Number");

        jLabel11.setText("Value");

        jLabel12.setText("Type");

        NumberType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Integer", "Long", "Float", "Double" }));

        javax.swing.GroupLayout NumberPanelLayout = new javax.swing.GroupLayout(NumberPanel);
        NumberPanel.setLayout(NumberPanelLayout);
        NumberPanelLayout.setHorizontalGroup(
            NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(NumberPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(NumberPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NumberPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumberType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        NumberPanelLayout.setVerticalGroup(
            NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(NumberType))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        Main.add(NumberPanel);
        NumberPanel.setBounds(0, 0, 400, 220);

        Apply.setText("Apply");
        Apply.setPreferredSize(new java.awt.Dimension(125, 30));
        Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyActionPerformed(evt);
            }
        });
        jPanel2.add(Apply);

        Cancel.setText("Cancel");
        Cancel.setPreferredSize(new java.awt.Dimension(125, 30));
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel2.add(Cancel);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 5));

        jButton_Image.setBackground(new java.awt.Color(204, 204, 255));
        jButton_Image.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Image.setText("Image");
        jButton_Image.setBorder(null);
        jButton_Image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImageActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Image);

        jButton_String.setBackground(new java.awt.Color(204, 204, 255));
        jButton_String.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_String.setText("String");
        jButton_String.setBorder(null);
        jButton_String.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StringActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_String);

        jButton_Number.setBackground(new java.awt.Color(204, 204, 255));
        jButton_Number.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Number.setText("Number");
        jButton_Number.setBorder(null);
        jButton_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NumberActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Number);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resize() {
        int width = Integer.parseInt(WidthTextField.getText());
        int height = Integer.parseInt(HeightTextField.getText());
        if (OriginalSize.isSelected()) {
            width = originalImage.getWidth();
            height = originalImage.getHeight();
        }
        resizedImage = new BufferedImage(width, height, originalImage.getType());
        Graphics2D g2d = resizedImage.createGraphics();
        g2d.drawImage(originalImage, 0, 0, width, height, null);
        g2d.dispose();
    }
    
    public static BufferedImage getBufferedImageFromJson(String base64Image) throws IOException {
        byte[] imageBytes = Base64.getDecoder().decode(base64Image); // Decode Base64

        // Change into BufferedImage
        try (ByteArrayInputStream bis = new ByteArrayInputStream(imageBytes)) {
            return ImageIO.read(bis);
        }
    }
    
    private void BrowseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseFileActionPerformed
        // TODO add your handling code here:
        
        
        JFileChooser fileChooser = new JFileChooser();
        // File Filter
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                }
                String name = f.getName().toLowerCase();
                return name.endsWith(".jpg") || name.endsWith(".jpeg") || 
                       name.endsWith(".png") || name.endsWith(".gif") || 
                       name.endsWith(".bmp");
            }

            @Override
            public String getDescription() {
                return "Image Files (*.jpg, *.jpeg, *.png, *.gif, *.bmp)";
            }
        });
        
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            // Selected file
            File selectedFile = fileChooser.getSelectedFile();
            PathField.setText(selectedFile.getAbsolutePath());
            try { 
                originalImage = ImageIO.read(selectedFile);
                resize();
            } catch (IOException ex) {
                Logger.getLogger(GetData.class.getName()).log(Level.SEVERE, null, ex);
            }
            // Check for file
            if (selectedFile.exists() && selectedFile.isFile()) {
                // 
                System.out.println("Valid file!");
            } else {
                System.out.println("Not a valid file.");
            }
        } else {
            System.out.println("No valid file.");
        }
        
        
    }//GEN-LAST:event_BrowseFileActionPerformed

    private void VIewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIewFileActionPerformed
        // TODO add your handling code here:
        if (originalImage != null) {
            Dialog frame = new Dialog(this,"Image Icon Example",Dialog.ModalityType.APPLICATION_MODAL);
            frame.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    frame.dispose(); // Ensure the dialog closes
                }
                });
            int width = Integer.parseInt(WidthTextField.getText());
            int height = Integer.parseInt(HeightTextField.getText());
            if (OriginalSize.isSelected()) {
                width = originalImage.getWidth();
                height = originalImage.getHeight();
            }
            frame.setSize(width+50, height+50);
            frame.setBounds(0, 0, width+100, height+100);
            frame.setLayout(null);
            frame.setLocationRelativeTo(null);

            ImageIcon originalIcon = new ImageIcon(resizedImage);

            Image scaledImage = originalIcon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            JLabel imageLabel = new JLabel(scaledIcon);
            imageLabel.setBounds(25, 25, width, height);
            frame.add(imageLabel);

            frame.setVisible(true);
        }
    }//GEN-LAST:event_VIewFileActionPerformed

    private void WidthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WidthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WidthTextFieldActionPerformed

    private static String bufferedImageToBase64(BufferedImage image) throws IOException {
        java.io.ByteArrayOutputStream outputStream = new java.io.ByteArrayOutputStream();
        ImageIO.write(image, "png", outputStream);
        byte[] imageBytes = outputStream.toByteArray();
        return Base64.getEncoder().encodeToString(imageBytes);
    }
    
    private void ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyActionPerformed
        if (mode == 0) {
            if (resizedImage != null) {
                int width = Integer.parseInt(WidthTextField.getText());
                int height = Integer.parseInt(HeightTextField.getText());
                if (OriginalSize.isSelected()) {
                    width = originalImage.getWidth();
                    height = originalImage.getHeight();
                }   
                String base64Image = null;
                try {
                    base64Image = bufferedImageToBase64(resizedImage);
                } catch (IOException ex) {
                    Logger.getLogger(GetData.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (SaveAsJSON.isSelected()) {
                    JSONObject image = new JSONObject();
                    image.put("data", base64Image); // Example base64 string
                    image.put("type", "png");
                    image.put("height", height);
                    image.put("width", width);
                    parent.updateTable(targetKey, image);
                } else {
                    parent.updateTable(targetKey, base64Image);
                }
            }
        } else if (mode == 1) {
            parent.updateTable(targetKey, jTextArea.getText());
        } else if (mode == 2) {
            int selected = NumberType.getSelectedIndex();
            Object value = null;
            if (selected == 0) {
                try {
                    value = Integer.parseInt(NumberField.getText());
                } catch (Exception e) {
                }
            } else if (selected == 1) {
                try {
                    value = Long.parseLong(NumberField.getText());
                } catch (Exception e) {
                }
            } else if (selected == 2) {
                try {
                    value = Float.parseFloat(NumberField.getText());
                } catch (Exception e) {
                }
            } else if (selected == 3) {
                try {
                    value = Double.parseDouble(NumberField.getText());
                } catch (Exception e) {
                }
            }
            parent.updateTable(targetKey, value);
        }
        this.dispose();
    }//GEN-LAST:event_ApplyActionPerformed

    private void VIewFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIewFile1ActionPerformed
        // TODO add your handling code here:
        // Open file chooser to select the save location and file type
        JFileChooser saveFileChooser = new JFileChooser();
        saveFileChooser.setDialogTitle("Save Resized Image");
        saveFileChooser.setSelectedFile(new File("resized_image.jpg")); // Default name and extension
        int saveResult = saveFileChooser.showSaveDialog(null);

        if (saveResult == JFileChooser.APPROVE_OPTION) {
            File saveFile = saveFileChooser.getSelectedFile();
            String filePath = saveFile.getAbsolutePath();
            String fileExtension = "png"; // Default to JPG

            // Check if the user specified an extension
            if (filePath.contains(".")) {
                fileExtension = filePath.substring(filePath.lastIndexOf('.') + 1).toLowerCase();
            } else {
                // Add default extension if none specified
                saveFile = new File(filePath + "." + fileExtension);
            }

            try {
                // Save the resized image
                ImageIO.write(resizedImage, fileExtension, saveFile);
            } catch (IOException ex) {
                Logger.getLogger(GetData.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Resized image saved at: " + saveFile.getAbsolutePath());
        } else {
            System.out.println("Save operation canceled.");
        }
    }//GEN-LAST:event_VIewFile1ActionPerformed

    private void WidthTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_WidthTextFieldPropertyChange
        // TODO add your handling code here:
        try {
            Integer.parseInt(WidthTextField.getText());
        } catch (Exception e) {
            WidthTextField.setText("50");
        }
        if (originalImage != null) {
            resize();
        }
    }//GEN-LAST:event_WidthTextFieldPropertyChange

    private void HeightTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_HeightTextFieldPropertyChange
        // TODO add your handling code here:
        try {
            Integer.parseInt(HeightTextField.getText());
        } catch (Exception e) {
            HeightTextField.setText("50");
        }
        if (originalImage != null) {
            resize();
        }
    }//GEN-LAST:event_HeightTextFieldPropertyChange

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void OriginalSizePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_OriginalSizePropertyChange
        // TODO add your handling code here:
        if (originalImage != null) {
            resize();
        }
    }//GEN-LAST:event_OriginalSizePropertyChange

    private void BrowseFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseFile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrowseFile1ActionPerformed

    private void WidthTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WidthTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WidthTextField1ActionPerformed

    private void WidthTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_WidthTextField1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_WidthTextField1PropertyChange

    private void HeightTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_HeightTextField1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightTextField1PropertyChange

    private void VIewFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIewFile2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VIewFile2ActionPerformed

    private void VIewFile3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIewFile3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VIewFile3ActionPerformed

    private void OriginalSize1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_OriginalSize1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_OriginalSize1PropertyChange

    private void jButton_ImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ImageActionPerformed
        // TODO add your handling code here:
        mode = 0;
        ImagePanel.setVisible(true);
        StringPanel.setVisible(false);
        NumberPanel.setVisible(false);
    }//GEN-LAST:event_jButton_ImageActionPerformed

    private void jButton_StringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StringActionPerformed
        // TODO add your handling code here:
        mode = 1;
        ImagePanel.setVisible(false);
        StringPanel.setVisible(true);
        NumberPanel.setVisible(false);
    }//GEN-LAST:event_jButton_StringActionPerformed

    private void jButton_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NumberActionPerformed
        // TODO add your handling code here:
        mode = 2;
        ImagePanel.setVisible(false);
        StringPanel.setVisible(false);
        NumberPanel.setVisible(true);
    }//GEN-LAST:event_jButton_NumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetData(null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apply;
    private javax.swing.JButton BrowseFile;
    private javax.swing.JButton BrowseFile1;
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField HeightTextField;
    private javax.swing.JTextField HeightTextField1;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JPanel ImagePanel1;
    private javax.swing.JPanel Main;
    private javax.swing.JTextField NumberField;
    private javax.swing.JPanel NumberPanel;
    private javax.swing.JComboBox<String> NumberType;
    private javax.swing.JCheckBox OriginalSize;
    private javax.swing.JCheckBox OriginalSize1;
    private javax.swing.JTextField PathField;
    private javax.swing.JTextField PathField1;
    private javax.swing.JCheckBox SaveAsJSON;
    private javax.swing.JCheckBox SaveAsJSON1;
    private javax.swing.JPanel StringPanel;
    private javax.swing.JButton VIewFile;
    private javax.swing.JButton VIewFile1;
    private javax.swing.JButton VIewFile2;
    private javax.swing.JButton VIewFile3;
    private javax.swing.JTextField WidthTextField;
    private javax.swing.JTextField WidthTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Image;
    private javax.swing.JButton jButton_Number;
    private javax.swing.JButton jButton_String;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
