/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.security.NoSuchAlgorithmException;
import java.util.*;
import java.lang.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;
import pc_builder.Device;
import pc_builder.TimeHandler;
import pc_builder.BuildPC;
import pc_builder.User;

/**
 *
 * @author Admin
 */


public class Home extends javax.swing.JFrame {
    Login parent;
    Vector<String> deviceTypes = new Vector<>();
    Vector<String> deviceBrands = new Vector<>();
    /**
     * Creates new form Home
     */
    
    private static void showWarningDialog(String title, String message) {
        JDialog dialog = new JDialog();
        dialog.setTitle(title);
        dialog.setModal(true);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        // Message panel
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // Add an icon and the message
        JLabel iconLabel = new JLabel(UIManager.getIcon("OptionPane.warningIcon"));
        JLabel messageLabel = new JLabel(message);

        panel.add(iconLabel, BorderLayout.WEST);
        panel.add(messageLabel, BorderLayout.CENTER);

        // Button to close the dialog
        JButton closeButton = new JButton("OK");
        closeButton.addActionListener(e -> dialog.dispose());
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(closeButton);

        panel.add(buttonPanel, BorderLayout.SOUTH);

        
        dialog.add(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }
    
    public Home(Login parent) {
        initComponents();
        this.parent = parent;
        HomeHello.setText(String.format("Hi, %s!",parent.currentUser.name));
        UsernamePanel.setText((String)parent.currentUser.getUsername());
        
        TreeSet<Object> types = Device.getDistinctValue("type");
        Vector<String> a = new Vector<String>();
        for (Object i: types) {
            a.add((String)i);
        }
        a.add("-All");
        Collections.sort(a);
        deviceTypes = (Vector<String>) a.clone();
        FillType.setModel(new javax.swing.DefaultComboBoxModel<>(a));
        
        types = Device.getDistinctValue("brand");
        a = new Vector<String>();
        for (Object i: types) {
            a.add((String)i);
        }
        a.add("-All");
        Collections.sort(a);
        deviceBrands = (Vector<String>) a.clone();
        FillBrand.setModel(new javax.swing.DefaultComboBoxModel<>(a));
        FillBrand1.setModel(new javax.swing.DefaultComboBoxModel<>(a));
        updateBalance();
        getSaleProduct();
    }

    public void updateBalance () {
        UsernamePanel.setText(parent.currentUser.getUsername()+" | $"+parent.currentUser.balance);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroupHomePage = new javax.swing.ButtonGroup();
        Main = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        HomePanelButtons = new javax.swing.JPanel();
        SaleButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        BuildButton = new javax.swing.JButton();
        NewsButton = new javax.swing.JButton();
        HomePageIcon = new javax.swing.JPanel();
        HomaPageButton = new javax.swing.JButton();
        UserPanel = new javax.swing.JPanel();
        UsernamePanel = new javax.swing.JLabel();
        UserButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        Content = new javax.swing.JPanel();
        HomePage = new javax.swing.JPanel();
        HomeHello = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        NewsPage = new javax.swing.JPanel();
        NewsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NewsItems = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        NewContent = new javax.swing.JPanel();
        NewTittle = new javax.swing.JLabel();
        NewData = new javax.swing.JPanel();
        SalePage = new javax.swing.JPanel();
        NewsPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        NewContent5 = new javax.swing.JPanel();
        NewTittle4 = new javax.swing.JLabel();
        SearchResult1 = new javax.swing.JScrollPane();
        SearchContent1 = new javax.swing.JPanel();
        SearchPage = new javax.swing.JPanel();
        NewsPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FillType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        FillBrand = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        FillName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        FillMax = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        FillMin = new javax.swing.JSpinner();
        Search = new javax.swing.JButton();
        NewContent7 = new javax.swing.JPanel();
        NewTittle6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        SearchContent = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        BuildPage = new javax.swing.JPanel();
        NewContent6 = new javax.swing.JPanel();
        NewTittle5 = new javax.swing.JLabel();
        SearchResult2 = new javax.swing.JScrollPane();
        BuildContent = new javax.swing.JPanel();
        NewsPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        FillBrand1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        FillMax1 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        FillMin1 = new javax.swing.JSpinner();
        BuildPC = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        DisplayMax = new javax.swing.JSpinner();
        CheapestBuild = new javax.swing.JCheckBox();
        PerformanceBuild = new javax.swing.JCheckBox();
        UserPage = new javax.swing.JPanel();
        NewsPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        NewsItems4 = new javax.swing.JScrollPane();
        User_Setting_List = new javax.swing.JList<>();
        NewContent4 = new javax.swing.JPanel();
        User_Setting_Tittle = new javax.swing.JLabel();
        NewData4 = new javax.swing.JPanel();
        User_MainSetting_Page = new javax.swing.JPanel();
        OldPasswordLabel = new javax.swing.JLabel();
        OldPasswordTextField = new javax.swing.JPasswordField();
        OldPasswordWarning = new javax.swing.JLabel();
        ReNewPasswordLabel = new javax.swing.JLabel();
        ReNewPasswordTextField = new javax.swing.JPasswordField();
        ReNewPasswordWarning = new javax.swing.JLabel();
        ReNewPasswordWarning.setVisible(false);
        jLabel1 = new javax.swing.JLabel();
        NewPasswordLabel = new javax.swing.JLabel();
        NewPasswordTextField = new javax.swing.JPasswordField();
        NewPasswordWarning = new javax.swing.JLabel();
        ApplyNewPasswordButton = new javax.swing.JButton();
        ApplyNewPasswordWarning = new javax.swing.JLabel();
        ApplyNewPasswordWarning.setVisible(false);
        User_Delete_Page = new javax.swing.JPanel();
        Delete_User_Button = new javax.swing.JButton();
        ConfirmDeleteAcc = new javax.swing.JCheckBox();
        User_History_Page = new javax.swing.JPanel();
        Delete_User_Button2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();

        ButtonGroupHomePage.add(NewsButton);
        ButtonGroupHomePage.add(SaleButton);
        ButtonGroupHomePage.add(SearchButton);
        ButtonGroupHomePage.add(BuildButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(254, 254, 254));
        setPreferredSize(new java.awt.Dimension(1215, 850));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close(evt);
            }
        });

        Main.setPreferredSize(new java.awt.Dimension(1200, 850));
        Main.setLayout(null);

        HomePanel.setBackground(new java.awt.Color(153, 153, 255));
        HomePanel.setMinimumSize(new java.awt.Dimension(1200, 65));
        HomePanel.setPreferredSize(new java.awt.Dimension(1200, 65));

        HomePanelButtons.setOpaque(false);
        HomePanelButtons.setPreferredSize(new java.awt.Dimension(780, 65));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEADING);
        flowLayout1.setAlignOnBaseline(true);
        HomePanelButtons.setLayout(flowLayout1);

        SaleButton.setBackground(new java.awt.Color(153, 153, 255));
        SaleButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SaleButton.setForeground(new java.awt.Color(255, 255, 255));
        SaleButton.setText("Sales");
        SaleButton.setBorder(null);
        SaleButton.setBorderPainted(false);
        SaleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaleButton.setFocusPainted(false);
        SaleButton.setPreferredSize(new java.awt.Dimension(150, 50));
        SaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleButtonActionPerformed(evt);
            }
        });
        HomePanelButtons.add(SaleButton);

        SearchButton.setBackground(new java.awt.Color(153, 153, 255));
        SearchButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchButton.setText("Search");
        SearchButton.setBorder(null);
        SearchButton.setBorderPainted(false);
        SearchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchButton.setFocusPainted(false);
        SearchButton.setPreferredSize(new java.awt.Dimension(150, 50));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        HomePanelButtons.add(SearchButton);

        BuildButton.setBackground(new java.awt.Color(153, 153, 255));
        BuildButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BuildButton.setForeground(new java.awt.Color(255, 255, 255));
        BuildButton.setText("Build PC");
        BuildButton.setBorder(null);
        BuildButton.setBorderPainted(false);
        BuildButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuildButton.setFocusPainted(false);
        BuildButton.setPreferredSize(new java.awt.Dimension(150, 50));
        BuildButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildButtonActionPerformed(evt);
            }
        });
        HomePanelButtons.add(BuildButton);

        NewsButton.setBackground(new java.awt.Color(153, 153, 255));
        NewsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewsButton.setForeground(new java.awt.Color(255, 255, 255));
        NewsButton.setText("News");
        NewsButton.setBorder(null);
        NewsButton.setBorderPainted(false);
        NewsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NewsButton.setEnabled(false);
        NewsButton.setFocusPainted(false);
        NewsButton.setPreferredSize(new java.awt.Dimension(150, 50));
        NewsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewsButtonActionPerformed(evt);
            }
        });
        HomePanelButtons.add(NewsButton);

        HomePageIcon.setBackground(new java.awt.Color(153, 153, 255));
        HomePageIcon.setPreferredSize(new java.awt.Dimension(300, 65));

        HomaPageButton.setBackground(new java.awt.Color(153, 153, 255));
        HomaPageButton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        HomaPageButton.setForeground(new java.awt.Color(255, 255, 255));
        HomaPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icon.png"))); // NOI18N
        HomaPageButton.setText("PC Builder");
        HomaPageButton.setBorder(null);
        HomaPageButton.setBorderPainted(false);
        HomaPageButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomaPageButton.setFocusPainted(false);
        HomaPageButton.setPreferredSize(new java.awt.Dimension(300, 65));
        HomaPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomaPageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomePageIconLayout = new javax.swing.GroupLayout(HomePageIcon);
        HomePageIcon.setLayout(HomePageIconLayout);
        HomePageIconLayout.setHorizontalGroup(
            HomePageIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomaPageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomePageIconLayout.setVerticalGroup(
            HomePageIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomaPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        UserPanel.setBackground(new java.awt.Color(153, 153, 255));
        UserPanel.setForeground(new java.awt.Color(51, 0, 255));
        UserPanel.setPreferredSize(new java.awt.Dimension(150, 65));

        UsernamePanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernamePanel.setForeground(new java.awt.Color(255, 255, 255));
        UsernamePanel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UsernamePanel.setText("Username");

        UserButton.setBackground(new java.awt.Color(153, 136, 252));
        UserButton.setForeground(new java.awt.Color(255, 255, 255));
        UserButton.setText("👤");
        UserButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        UserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserButton.setPreferredSize(new java.awt.Dimension(30, 30));
        UserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(102, 0, 204));
        LogoutButton.setText("Logout");
        LogoutButton.setBorder(null);
        LogoutButton.setBorderPainted(false);
        LogoutButton.setContentAreaFilled(false);
        LogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LogoutButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserPanelLayout = new javax.swing.GroupLayout(UserPanel);
        UserPanel.setLayout(UserPanelLayout);
        UserPanelLayout.setHorizontalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserPanelLayout.createSequentialGroup()
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserPanelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(LogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(UserPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UsernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        UserPanelLayout.setVerticalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserPanelLayout.createSequentialGroup()
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UserPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(UsernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addComponent(HomePageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomePanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HomePanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addComponent(HomePageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(UserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Main.add(HomePanel);
        HomePanel.setBounds(0, 0, 1200, 65);

        Content.setPreferredSize(new java.awt.Dimension(1200, 735));
        Content.setLayout(null);

        HomePage.setPreferredSize(new java.awt.Dimension(1200, 735));

        HomeHello.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HomeHello.setText("Hi, <Username>!");

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setFocusable(false);

        jTextPane1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextPane1.setText("Welcome to PC Builder – Your Ultimate PC Building Companion! 🎮💻\n\nAre you ready to bring your dream PC to life? Whether you're aiming for a gaming beast, a creative powerhouse, or an all-purpose workhorse, we’re here to make the process seamless, fun, and tailored just for you.\n\n🔧 Build Your Custom PC:\nChoose from the latest and most reliable components to design a system that perfectly fits your needs.\n\n💡 Expert Recommendations:\nNot sure where to start? Our smart guides and expert tips will help you pick the best parts for your budget and requirements.\n\n💰 Budget-Friendly Options:\nTrack your expenses as you go and find the perfect balance between performance and cost.\n\n⚡ Seamless Compatibility Checks:\nWe ensure all your selected components work together flawlessly, so you can build with confidence.\n\n🏆 Why Choose Us?\n\nStay up-to-date with the latest hardware trends.\nAccess detailed specs and performance benchmarks.\nGet real-time support if you need a hand.\nStart your journey to building the perfect PC today! From novice builders to seasoned pros, we’ve got everything you need to succeed.");
        jTextPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextPane1.setFocusCycleRoot(false);
        jTextPane1.setFocusable(false);
        jTextPane1.setOpaque(false);
        jTextPane1.setRequestFocusEnabled(false);
        jTextPane1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout HomePageLayout = new javax.swing.GroupLayout(HomePage);
        HomePage.setLayout(HomePageLayout);
        HomePageLayout.setHorizontalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                    .addGroup(HomePageLayout.createSequentialGroup()
                        .addComponent(HomeHello, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HomePageLayout.setVerticalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeHello, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Content.add(HomePage);
        HomePage.setBounds(0, 0, 1200, 735);

        NewsPage.setPreferredSize(new java.awt.Dimension(1200, 735));
        NewsPage.setVisible(false);

        NewsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setBackground(new java.awt.Color(153, 153, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText(" What's new?");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255)));
        jLabel3.setOpaque(true);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        NewsItems.setViewportView(jList1);

        javax.swing.GroupLayout NewsPanelLayout = new javax.swing.GroupLayout(NewsPanel);
        NewsPanel.setLayout(NewsPanelLayout);
        NewsPanelLayout.setHorizontalGroup(
            NewsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(NewsItems))
                .addContainerGap())
        );
        NewsPanelLayout.setVerticalGroup(
            NewsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewsItems, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );

        NewContent.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        NewTittle.setBackground(new java.awt.Color(204, 204, 255));
        NewTittle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewTittle.setText(" Tittle");
        NewTittle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NewTittle.setOpaque(true);

        NewData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NewData.setLayout(null);

        javax.swing.GroupLayout NewContentLayout = new javax.swing.GroupLayout(NewContent);
        NewContent.setLayout(NewContentLayout);
        NewContentLayout.setHorizontalGroup(
            NewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewTittle, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE))
                .addContainerGap())
        );
        NewContentLayout.setVerticalGroup(
            NewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout NewsPageLayout = new javax.swing.GroupLayout(NewsPage);
        NewsPage.setLayout(NewsPageLayout);
        NewsPageLayout.setHorizontalGroup(
            NewsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        NewsPageLayout.setVerticalGroup(
            NewsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Content.add(NewsPage);
        NewsPage.setBounds(0, 0, 1200, 735);

        SalePage.setPreferredSize(new java.awt.Dimension(1200, 735));
        SalePage.setVisible(false);

        NewsPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText(" On Sale products!");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255)));
        jLabel4.setOpaque(true);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Look like some product have a sale!\nGet your favourite product with sale in here!");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout NewsPanel1Layout = new javax.swing.GroupLayout(NewsPanel1);
        NewsPanel1.setLayout(NewsPanel1Layout);
        NewsPanel1Layout.setHorizontalGroup(
            NewsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewsPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        NewsPanel1Layout.setVerticalGroup(
            NewsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );

        NewContent5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NewContent5.setPreferredSize(new java.awt.Dimension(857, 63));
        NewContent5.setRequestFocusEnabled(false);

        NewTittle4.setBackground(new java.awt.Color(204, 204, 255));
        NewTittle4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewTittle4.setText(" Result:");
        NewTittle4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NewTittle4.setOpaque(true);

        SearchResult1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        SearchResult1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        SearchContent1.setBackground(new java.awt.Color(221, 221, 221));
        SearchContent1.setFocusable(false);
        SearchContent1.setPreferredSize(new java.awt.Dimension(800, 1200));
        SearchContent1.setLayout(new javax.swing.BoxLayout(SearchContent1, javax.swing.BoxLayout.PAGE_AXIS));
        SearchResult1.setViewportView(SearchContent1);

        javax.swing.GroupLayout NewContent5Layout = new javax.swing.GroupLayout(NewContent5);
        NewContent5.setLayout(NewContent5Layout);
        NewContent5Layout.setHorizontalGroup(
            NewContent5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewContent5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewContent5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewTittle4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchResult1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE))
                .addContainerGap())
        );
        NewContent5Layout.setVerticalGroup(
            NewContent5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewContent5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewTittle4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchResult1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout SalePageLayout = new javax.swing.GroupLayout(SalePage);
        SalePage.setLayout(SalePageLayout);
        SalePageLayout.setHorizontalGroup(
            SalePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewContent5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SalePageLayout.setVerticalGroup(
            SalePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalePageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SalePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewContent5, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                    .addComponent(NewsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Content.add(SalePage);
        SalePage.setBounds(0, 0, 1200, 735);

        SearchPage.setPreferredSize(new java.awt.Dimension(1200, 735));
        SearchPage.setVisible(false);

        NewsPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setBackground(new java.awt.Color(153, 153, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText(" Searching");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255)));
        jLabel5.setOpaque(true);

        jLabel2.setText("Type:");

        FillType.setBackground(new java.awt.Color(254, 254, 254));
        FillType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Mouse", " " }));

        jLabel8.setText("Brand:");

        FillBrand.setBackground(new java.awt.Color(254, 254, 254));
        FillBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Mouse", " " }));

        jLabel9.setText("Filter: ");

        jLabel10.setText("Max:");

        FillMax.setValue(Integer.MAX_VALUE);

        jLabel12.setText("Min:");

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewsPanel2Layout = new javax.swing.GroupLayout(NewsPanel2);
        NewsPanel2.setLayout(NewsPanel2Layout);
        NewsPanel2Layout.setHorizontalGroup(
            NewsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(NewsPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FillMax))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(NewsPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FillType, 0, 217, Short.MAX_VALUE))
                    .addGroup(NewsPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FillBrand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(NewsPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FillName))
                    .addGroup(NewsPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FillMin)))
                .addContainerGap())
        );
        NewsPanel2Layout.setVerticalGroup(
            NewsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FillType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FillBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FillName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(FillMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FillMin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        NewContent7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        NewTittle6.setBackground(new java.awt.Color(204, 204, 255));
        NewTittle6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewTittle6.setText(" Result:");
        NewTittle6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NewTittle6.setOpaque(true);

        jScrollPane3.getVerticalScrollBar().setUnitIncrement(10);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        SearchContent.setBackground(new java.awt.Color(221, 221, 221));
        SearchContent.setPreferredSize(new java.awt.Dimension(800, 1200));
        SearchContent.setLayout(new javax.swing.BoxLayout(SearchContent, javax.swing.BoxLayout.PAGE_AXIS));

        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        SearchContent.add(jToggleButton1);

        jScrollPane3.setViewportView(SearchContent);

        javax.swing.GroupLayout NewContent7Layout = new javax.swing.GroupLayout(NewContent7);
        NewContent7.setLayout(NewContent7Layout);
        NewContent7Layout.setHorizontalGroup(
            NewContent7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewContent7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewContent7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewTittle6, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        NewContent7Layout.setVerticalGroup(
            NewContent7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewContent7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewTittle6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout SearchPageLayout = new javax.swing.GroupLayout(SearchPage);
        SearchPage.setLayout(SearchPageLayout);
        SearchPageLayout.setHorizontalGroup(
            SearchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewContent7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SearchPageLayout.setVerticalGroup(
            SearchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewContent7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Content.add(SearchPage);
        SearchPage.setBounds(0, 0, 1200, 735);

        BuildPage.setPreferredSize(new java.awt.Dimension(1200, 735));
        BuildPage.setVisible(false);

        NewContent6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        NewTittle5.setBackground(new java.awt.Color(204, 204, 255));
        NewTittle5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NewTittle5.setText(" Result:");
        NewTittle5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NewTittle5.setOpaque(true);

        SearchResult2.getVerticalScrollBar().setUnitIncrement(10);
        SearchResult2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        SearchResult2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        BuildContent.setBackground(new java.awt.Color(232, 232, 232));
        BuildContent.setFocusable(false);
        BuildContent.setPreferredSize(new java.awt.Dimension(800, 658));
        BuildContent.setLayout(new javax.swing.BoxLayout(BuildContent, javax.swing.BoxLayout.PAGE_AXIS));
        SearchResult2.setViewportView(BuildContent);

        javax.swing.GroupLayout NewContent6Layout = new javax.swing.GroupLayout(NewContent6);
        NewContent6.setLayout(NewContent6Layout);
        NewContent6Layout.setHorizontalGroup(
            NewContent6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewContent6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewContent6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SearchResult2, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                    .addComponent(NewTittle5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        NewContent6Layout.setVerticalGroup(
            NewContent6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewContent6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewTittle5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchResult2)
                .addContainerGap())
        );

        NewsPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setBackground(new java.awt.Color(153, 153, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Build your PC");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255)));
        jLabel11.setOpaque(true);

        jLabel14.setText("Brand:");

        FillBrand1.setBackground(new java.awt.Color(254, 254, 254));
        FillBrand1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Mouse", " " }));

        jLabel16.setText("Max:");

        FillMax1.setValue(Integer.MAX_VALUE);

        jLabel17.setText("Display Max:");

        BuildPC.setText("Build PC");
        BuildPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildPCActionPerformed(evt);
            }
        });

        jLabel18.setText("Min:");

        DisplayMax.setValue(10);

        CheapestBuild.setText("Cheapest");

        PerformanceBuild.setText("Best performance");

        javax.swing.GroupLayout NewsPanel5Layout = new javax.swing.GroupLayout(NewsPanel5);
        NewsPanel5.setLayout(NewsPanel5Layout);
        NewsPanel5Layout.setHorizontalGroup(
            NewsPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewsPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BuildPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(NewsPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FillMax1))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(NewsPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FillBrand1, 0, 217, Short.MAX_VALUE))
                    .addGroup(NewsPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FillMin1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewsPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisplayMax, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NewsPanel5Layout.createSequentialGroup()
                        .addGroup(NewsPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PerformanceBuild)
                            .addComponent(CheapestBuild))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        NewsPanel5Layout.setVerticalGroup(
            NewsPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewsPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FillBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewsPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FillMax1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewsPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FillMin1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheapestBuild, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PerformanceBuild)
                .addGap(34, 34, 34)
                .addGroup(NewsPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayMax, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuildPC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BuildPageLayout = new javax.swing.GroupLayout(BuildPage);
        BuildPage.setLayout(BuildPageLayout);
        BuildPageLayout.setHorizontalGroup(
            BuildPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuildPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewsPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(NewContent6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BuildPageLayout.setVerticalGroup(
            BuildPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuildPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuildPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewsPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewContent6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Content.add(BuildPage);
        BuildPage.setBounds(0, 0, 1200, 735);

        UserPage.setPreferredSize(new java.awt.Dimension(1200, 735));
        UserPage.setVisible(false);

        NewsPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setBackground(new java.awt.Color(153, 153, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText(" User Settings");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255)));
        jLabel7.setOpaque(true);

        User_Setting_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Main Setting", "Delete Account", "History" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        User_Setting_List.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                User_Setting_ListValueChanged(evt);
            }
        });
        NewsItems4.setViewportView(User_Setting_List);

        javax.swing.GroupLayout NewsPanel4Layout = new javax.swing.GroupLayout(NewsPanel4);
        NewsPanel4.setLayout(NewsPanel4Layout);
        NewsPanel4Layout.setHorizontalGroup(
            NewsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(NewsItems4))
                .addContainerGap())
        );
        NewsPanel4Layout.setVerticalGroup(
            NewsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewsPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewsItems4, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );

        NewContent4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        User_Setting_Tittle.setBackground(new java.awt.Color(204, 204, 255));
        User_Setting_Tittle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        User_Setting_Tittle.setText(" Tittle");
        User_Setting_Tittle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        User_Setting_Tittle.setOpaque(true);

        NewData4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NewData4.setLayout(null);

        User_MainSetting_Page.setVisible(false);
        User_MainSetting_Page.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        OldPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OldPasswordLabel.setText("Old Password");

        OldPasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                OldPasswordTextFieldFocusLost(evt);
            }
        });

        OldPasswordWarning.setVisible(false);
        OldPasswordWarning.setForeground(new java.awt.Color(255, 51, 0));
        OldPasswordWarning.setText("Username must have atleast 10 characters");

        ReNewPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ReNewPasswordLabel.setText("Re-enter New Password");

        ReNewPasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ReNewPasswordTextFieldFocusLost(evt);
            }
        });

        ReNewPasswordWarning.setForeground(new java.awt.Color(255, 51, 0));
        ReNewPasswordWarning.setText("Password not match");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Change password");

        NewPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewPasswordLabel.setText("New Password");

        NewPasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewPasswordTextFieldFocusLost(evt);
            }
        });

        NewPasswordWarning.setVisible(false);
        NewPasswordWarning.setForeground(new java.awt.Color(255, 51, 0));
        NewPasswordWarning.setText("Username must have atleast 10 characters");

        ApplyNewPasswordButton.setBackground(new java.awt.Color(102, 102, 255));
        ApplyNewPasswordButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ApplyNewPasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        ApplyNewPasswordButton.setText("Apply");
        ApplyNewPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyNewPasswordButtonActionPerformed(evt);
            }
        });

        ApplyNewPasswordWarning.setForeground(new java.awt.Color(255, 51, 0));
        ApplyNewPasswordWarning.setText("Please correct all container");

        javax.swing.GroupLayout User_MainSetting_PageLayout = new javax.swing.GroupLayout(User_MainSetting_Page);
        User_MainSetting_Page.setLayout(User_MainSetting_PageLayout);
        User_MainSetting_PageLayout.setHorizontalGroup(
            User_MainSetting_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_MainSetting_PageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(User_MainSetting_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ApplyNewPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReNewPasswordWarning)
                    .addComponent(OldPasswordLabel)
                    .addComponent(OldPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReNewPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReNewPasswordLabel)
                    .addComponent(OldPasswordWarning)
                    .addComponent(NewPasswordLabel)
                    .addComponent(NewPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewPasswordWarning)
                    .addComponent(ApplyNewPasswordWarning))
                .addContainerGap(523, Short.MAX_VALUE))
        );
        User_MainSetting_PageLayout.setVerticalGroup(
            User_MainSetting_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_MainSetting_PageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OldPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OldPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OldPasswordWarning)
                .addGap(18, 18, 18)
                .addComponent(NewPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewPasswordWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReNewPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReNewPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ReNewPasswordWarning)
                .addGap(1, 1, 1)
                .addComponent(ApplyNewPasswordWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ApplyNewPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        NewData4.add(User_MainSetting_Page);
        User_MainSetting_Page.setBounds(0, 0, 875, 658);

        User_Delete_Page.setVisible(false);
        User_Delete_Page.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Delete_User_Button.setBackground(new java.awt.Color(102, 102, 255));
        Delete_User_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delete_User_Button.setForeground(new java.awt.Color(255, 255, 255));
        Delete_User_Button.setText("Delete User Account");
        Delete_User_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_User_ButtonActionPerformed(evt);
            }
        });

        ConfirmDeleteAcc.setText("Confirm Delete Account");

        javax.swing.GroupLayout User_Delete_PageLayout = new javax.swing.GroupLayout(User_Delete_Page);
        User_Delete_Page.setLayout(User_Delete_PageLayout);
        User_Delete_PageLayout.setHorizontalGroup(
            User_Delete_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_Delete_PageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(User_Delete_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Delete_User_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmDeleteAcc))
                .addContainerGap(640, Short.MAX_VALUE))
        );
        User_Delete_PageLayout.setVerticalGroup(
            User_Delete_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_Delete_PageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConfirmDeleteAcc)
                .addGap(5, 5, 5)
                .addComponent(Delete_User_Button)
                .addContainerGap(596, Short.MAX_VALUE))
        );

        NewData4.add(User_Delete_Page);
        User_Delete_Page.setBounds(0, 0, 875, 658);

        User_History_Page.setVisible(false);
        User_History_Page.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Delete_User_Button2.setBackground(new java.awt.Color(102, 102, 255));
        Delete_User_Button2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delete_User_Button2.setForeground(new java.awt.Color(255, 255, 255));
        Delete_User_Button2.setText("Load History");
        Delete_User_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_User_Button2ActionPerformed(evt);
            }
        });

        HistoryTable.setBackground(new java.awt.Color(254, 254, 254));
        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index", "Date", "Time", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        HistoryTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(HistoryTable);
        if (HistoryTable.getColumnModel().getColumnCount() > 0) {
            HistoryTable.getColumnModel().getColumn(0).setMinWidth(50);
            HistoryTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            HistoryTable.getColumnModel().getColumn(0).setMaxWidth(50);
            HistoryTable.getColumnModel().getColumn(1).setMinWidth(100);
            HistoryTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            HistoryTable.getColumnModel().getColumn(1).setMaxWidth(100);
            HistoryTable.getColumnModel().getColumn(2).setMinWidth(100);
            HistoryTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            HistoryTable.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        javax.swing.GroupLayout User_History_PageLayout = new javax.swing.GroupLayout(User_History_Page);
        User_History_Page.setLayout(User_History_PageLayout);
        User_History_PageLayout.setHorizontalGroup(
            User_History_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_History_PageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(User_History_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_User_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        User_History_PageLayout.setVerticalGroup(
            User_History_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_History_PageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Delete_User_Button2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        NewData4.add(User_History_Page);
        User_History_Page.setBounds(0, 0, 875, 658);

        javax.swing.GroupLayout NewContent4Layout = new javax.swing.GroupLayout(NewContent4);
        NewContent4.setLayout(NewContent4Layout);
        NewContent4Layout.setHorizontalGroup(
            NewContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewContent4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewData4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(User_Setting_Tittle, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE))
                .addContainerGap())
        );
        NewContent4Layout.setVerticalGroup(
            NewContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewContent4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(User_Setting_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewData4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout UserPageLayout = new javax.swing.GroupLayout(UserPage);
        UserPage.setLayout(UserPageLayout);
        UserPageLayout.setHorizontalGroup(
            UserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewsPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewContent4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        UserPageLayout.setVerticalGroup(
            UserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewContent4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewsPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Content.add(UserPage);
        UserPage.setBounds(0, 0, 1200, 735);

        Main.add(Content);
        Content.setBounds(0, 65, 1200, 735);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("HomePage");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hidePage() {
        HomePage.setVisible(false);
        NewsPage.setVisible(false);
        SalePage.setVisible(false);
        SearchPage.setVisible(false);
        BuildPage.setVisible(false);
        UserPage.setVisible(false);
    }
    
    private void close(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_close
        // TODO add your handling code here:
        parent.close();
    }//GEN-LAST:event_close

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        parent.close();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void UserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserButtonActionPerformed
        // TODO add your handling code here:
        hidePage();
        UserPage.setVisible(true);
    }//GEN-LAST:event_UserButtonActionPerformed

    private void HomaPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomaPageButtonActionPerformed
        // TODO add your handling code here:
        hidePage();
        HomePage.setVisible(true);
    }//GEN-LAST:event_HomaPageButtonActionPerformed

    private void BuildButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildButtonActionPerformed
        // TODO add your handling code here:
        hidePage();
        BuildPage.setVisible(true);
    }//GEN-LAST:event_BuildButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        hidePage();
        SearchPage.setVisible(true);
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void SaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleButtonActionPerformed
        // TODO add your handling code here:
        hidePage();
        SalePage.setVisible(true);
    }//GEN-LAST:event_SaleButtonActionPerformed

    private void NewsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewsButtonActionPerformed
        // TODO add your handling code here:
        hidePage();
        NewsPage.setVisible(true);
    }//GEN-LAST:event_NewsButtonActionPerformed

    private void Delete_User_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_User_ButtonActionPerformed
        // TODO add your handling code here:
        if (ConfirmDeleteAcc.isSelected()) {
            User.deleteUser(parent.currentUser.getUsername());
            parent.close();
        }
    }//GEN-LAST:event_Delete_User_ButtonActionPerformed

    private void User_Setting_ListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_User_Setting_ListValueChanged
        // TODO add your handling code here:
        User_Delete_Page.setVisible(false);
        User_MainSetting_Page.setVisible(false);
        User_History_Page.setVisible(false);
        int index = User_Setting_List.getSelectedIndex();
        if (index == 0) {
            User_MainSetting_Page.setVisible(true);
            User_Setting_Tittle.setText(User_Setting_List.getSelectedValue());
        } else if (index == 1) {
            User_Delete_Page.setVisible(true);
            User_Setting_Tittle.setText(User_Setting_List.getSelectedValue());
        } else if (index == 2) {
            User_History_Page.setVisible(true);
            User_Setting_Tittle.setText(User_Setting_List.getSelectedValue());
        } 
    }//GEN-LAST:event_User_Setting_ListValueChanged

    private void OldPasswordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OldPasswordTextFieldFocusLost
        // TODO add your handling code here:
        OldPasswordWarning.setVisible(false);
        String content = String.copyValueOf(OldPasswordTextField.getPassword());
        if (content.length()==0) {
            OldPasswordWarning.setText("Password cannot leave blank");
            OldPasswordWarning.setVisible(true);
        } else {
            try {
                if (parent.currentUser.logIn(content)) {
                    
                } else {
                    OldPasswordWarning.setText("Wrong password!");
                    OldPasswordWarning.setVisible(true);
                }
            } catch (NoSuchAlgorithmException ex) {
                
            }
        }
    }//GEN-LAST:event_OldPasswordTextFieldFocusLost

    private void ReNewPasswordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ReNewPasswordTextFieldFocusLost
        // TODO add your handling code here:
        String firstPass = String.copyValueOf(NewPasswordTextField.getPassword());
        String secondPass = String.copyValueOf(ReNewPasswordTextField.getPassword());
        ReNewPasswordWarning.setVisible(false);
        if (secondPass.compareTo(firstPass)!=0) {
            ReNewPasswordWarning.setText("Password not match");
            ReNewPasswordWarning.setVisible(true);
        }
    }//GEN-LAST:event_ReNewPasswordTextFieldFocusLost

    private void NewPasswordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewPasswordTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPasswordTextFieldFocusLost

    public void purchase(String id) {
        Device device = Device.getDevice(id);
        double price = device.truePrice;
        double userBalance = parent.currentUser.balance;
        if (userBalance<price) {
            showWarningDialog("Purchase failed!", "Your balance is not enough...");
        } else {
            showWarningDialog("Purchase complete!",String.format("You purchased a %s for $%.2f", device.getName(), price));
            userBalance -= price;
            parent.currentUser.balance = userBalance;
            parent.currentUser.addRecord(String.format("User purchase [%s:%s] for [%.2f]",id,device.getName(),price));
            parent.currentUser.update();
            updateBalance();
        }
    }
    
    public void purchaseSets(ArrayList<String> devices, double price) {
        double userBalance = parent.currentUser.balance;
        if (userBalance<price) {
            showWarningDialog("Purchase failed!", "Your balance is not enough...");
        } else {
            showWarningDialog("Purchase complete!",String.format("You purchased a set for $%.2f", price));
            userBalance -= price;
            for (String id: devices) {
                Device device = Device.getDevice(id);
                parent.currentUser.balance = userBalance;
                parent.currentUser.addRecord(String.format("User purchase [%s:%s] for [%.2f]",device.getId(),device.getName(),device.truePrice));
            }
            parent.currentUser.update();
            updateBalance();
        }
    }
    
    private void ApplyNewPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyNewPasswordButtonActionPerformed
        try {
            // TODO add your handling code here:
            ApplyNewPasswordWarning.setVisible(false);
            if (NewPasswordWarning.isVisible()) {
                ApplyNewPasswordWarning.setVisible(true);
                return;
            }
            if (OldPasswordWarning.isVisible()) {
                ApplyNewPasswordWarning.setVisible(true);
                return;
            }
            if (ReNewPasswordWarning.isVisible()) {
                ApplyNewPasswordWarning.setVisible(true);
                return;
            }
            if (parent.currentUser.logIn(String.copyValueOf(OldPasswordTextField.getPassword()))) {
                if (String.copyValueOf(ReNewPasswordTextField.getPassword()).compareTo(String.copyValueOf(NewPasswordTextField.getPassword()))==0) {
                    String hashedPassword = User.hashPassword(String.copyValueOf(NewPasswordTextField.getPassword()));
                    parent.currentUser.data.put("password", hashedPassword);
                    parent.currentUser.update();
                    System.out.println("User password changed!");
                }
            }
        } catch (NoSuchAlgorithmException ex) {
        
        }
    }//GEN-LAST:event_ApplyNewPasswordButtonActionPerformed

    private void BuildPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildPCActionPerformed
        // TODO add your handling code here:
        BuildContent.removeAll();
        String pcBuildComponent[] = {"Case","Monitor","Key Board","Mouse"}; 
        TreeMap<String, Boolean> check = new TreeMap<>();
        TreeMap<String, ArrayList<Device>> getDevices = new TreeMap<>();
        for (String i: deviceTypes) {
            check.put(i, false);
        }
        for (String i: pcBuildComponent) {
            check.put(i, true);
        }
        
        Boolean getAllBrand = (boolean) (FillBrand1.getSelectedIndex()==0);
        
        // list all necessary device into a list inside a map
        for (String i: pcBuildComponent) {
            getDevices.put(i, new ArrayList<>());
        }
        
        for (String id: Device.items.keySet()) {
            Device item = Device.getDevice(id);
            if (check.get(item.getType())) {
                if (getAllBrand || FillBrand1.getSelectedItem().toString().compareTo(item.getType())==0) {
                    getDevices.get(item.getType()).add(item);
                }
            }
        }
        
        // Generate algorithm
        boolean isCheapest = CheapestBuild.isSelected();
        boolean isPerformance = PerformanceBuild.isSelected();
        
        
        
        boolean flag = true;
        int[] sinh = new int[pcBuildComponent.length];
        int pointer = 0;
        int l = sinh.length;
        ArrayList<BuildPC> res = new ArrayList<>();
        for (int key = 0; key < pcBuildComponent.length; key++) {
            ArrayList<Device> i = getDevices.get(pcBuildComponent[key]);
        }
        
        while (flag) {
            ArrayList<String> component = new ArrayList<>();
            for (int i=0; i<sinh.length; i++) {
                component.add(getDevices.get(pcBuildComponent[i]).get(sinh[i]).getId());
            }
            res.add(new BuildPC(component));
            pointer = 0;
            sinh[pointer]++;
            if (sinh[pointer]>=getDevices.get(pcBuildComponent[pointer]).size()) {
                while (sinh[pointer]>=getDevices.get(pcBuildComponent[pointer]).size()) {
                    sinh[pointer] = 0;
                    pointer++;
                    if (pointer >= l) {
                        flag = false;
                        break;
                    }
                    sinh[pointer]++;
                }
            }
        } 
        
        res.sort(new Comparator<BuildPC> (){
            @Override
            public int compare(BuildPC o1, BuildPC o2) {
                int res = 0;
                if (isCheapest) {
                    res = Double.compare(o1.price, o2.price);
                }
                if (res == 0 && isPerformance) {
                    res = Double.compare(o2.performance, o1.performance);
                }
                return res;
            }
            
        });
        // Create item frame
        
        int counter = 0;
        int maxDisplay = Integer.parseInt(DisplayMax.getValue().toString());
        for (BuildPC i: res) {
            if (i.price>=Double.parseDouble(FillMin1.getValue().toString()) && i.price<=Double.parseDouble(FillMax1.getValue().toString())) {
                //System.out.print("Price "+i.price+"  ");
                //i.print();
                counter++;
                BuildedPC item = new BuildedPC(this,counter,i.price,i.component);
                item.setVisible(true);
                BuildContent.add(item);
            }
            if (counter>=maxDisplay) {
                break;
            }
        }
        BuildContent.setPreferredSize(new Dimension(800,240*counter));
        BuildContent.revalidate();
    }//GEN-LAST:event_BuildPCActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        SearchContent.removeAll();
        ArrayList<String> a = new ArrayList<>();
        Boolean getAllType = (boolean) (FillType.getSelectedIndex()==0);
        Boolean getAllBrand = (boolean) (FillBrand.getSelectedIndex()==0);
        for (Device item: Device.items.values()) {
            if ((getAllType || FillType.getSelectedItem().toString().compareTo(item.getType())==0) && (getAllBrand || FillBrand.getSelectedItem().toString().compareTo(item.getBrand())==0) && (item.getName().contains(FillName.getText())) && item.truePrice>=(int)FillMin.getValue() && item.truePrice<=(int)FillMax.getValue() ) {
                a.add(item.getId());
            }
        }
        a.sort(new Comparator<String>() {
            @Override
            public int compare(String a, String b) {
                return Device.items.get(a).getName().compareTo(Device.items.get(b).getName());
            }
        });
        for (String i: a) {
            SearchItem item = new SearchItem(this, i);
            item.setVisible(true);
            SearchContent.add(item);
        }
        SearchContent.setPreferredSize(new Dimension(800,80*a.size()));
        SearchButton.transferFocus();
        SearchContent.revalidate();
    }//GEN-LAST:event_SearchActionPerformed

    private void Delete_User_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_User_Button2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabelModel = (DefaultTableModel)HistoryTable.getModel();
        tabelModel.setRowCount(0);
        JSONObject historyObject = parent.currentUser.getHistory();
        for (String key : historyObject.keySet()) {
            String data[] = {key, historyObject.getJSONObject(key).getString("date"), historyObject.getJSONObject(key).getString("time"), historyObject.getJSONObject(key).getString("action")};
            tabelModel.addRow(data);
        }
    }//GEN-LAST:event_Delete_User_Button2ActionPerformed

    public void getSaleProduct() {
        SearchContent1.removeAll();
        JSONArray getDevices = Device.dataArray;
        ArrayList<String> a = new ArrayList<>();
        for (Device i: Device.items.values()) {
            if (i.isForSale()){
                a.add(i.getId());
            }
        }
        a.sort(new Comparator<String>() {
            @Override
            public int compare(String a, String b) {
                return Device.items.get(a).getName().compareTo(Device.items.get(b).getName());
            }
        });
        for (String i: a) {
            SearchItem item = new SearchItem(this, i);
            item.setVisible(true);
            SearchContent1.add(item);
        }
        SearchContent1.setPreferredSize(new Dimension(800,80*a.size()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyNewPasswordButton;
    private javax.swing.JLabel ApplyNewPasswordWarning;
    private javax.swing.JButton BuildButton;
    private javax.swing.JPanel BuildContent;
    private javax.swing.JButton BuildPC;
    private javax.swing.JPanel BuildPage;
    private javax.swing.ButtonGroup ButtonGroupHomePage;
    private javax.swing.JCheckBox CheapestBuild;
    private javax.swing.JCheckBox ConfirmDeleteAcc;
    private javax.swing.JPanel Content;
    private javax.swing.JButton Delete_User_Button;
    private javax.swing.JButton Delete_User_Button2;
    private javax.swing.JSpinner DisplayMax;
    private javax.swing.JComboBox<String> FillBrand;
    private javax.swing.JComboBox<String> FillBrand1;
    private javax.swing.JSpinner FillMax;
    private javax.swing.JSpinner FillMax1;
    private javax.swing.JSpinner FillMin;
    private javax.swing.JSpinner FillMin1;
    private javax.swing.JTextField FillName;
    private javax.swing.JComboBox<String> FillType;
    private javax.swing.JTable HistoryTable;
    private javax.swing.JButton HomaPageButton;
    private javax.swing.JLabel HomeHello;
    private javax.swing.JPanel HomePage;
    private javax.swing.JPanel HomePageIcon;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel HomePanelButtons;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel NewContent;
    private javax.swing.JPanel NewContent4;
    private javax.swing.JPanel NewContent5;
    private javax.swing.JPanel NewContent6;
    private javax.swing.JPanel NewContent7;
    private javax.swing.JPanel NewData;
    private javax.swing.JPanel NewData4;
    private javax.swing.JLabel NewPasswordLabel;
    private javax.swing.JPasswordField NewPasswordTextField;
    private javax.swing.JLabel NewPasswordWarning;
    private javax.swing.JLabel NewTittle;
    private javax.swing.JLabel NewTittle4;
    private javax.swing.JLabel NewTittle5;
    private javax.swing.JLabel NewTittle6;
    private javax.swing.JButton NewsButton;
    private javax.swing.JScrollPane NewsItems;
    private javax.swing.JScrollPane NewsItems4;
    private javax.swing.JPanel NewsPage;
    private javax.swing.JPanel NewsPanel;
    private javax.swing.JPanel NewsPanel1;
    private javax.swing.JPanel NewsPanel2;
    private javax.swing.JPanel NewsPanel4;
    private javax.swing.JPanel NewsPanel5;
    private javax.swing.JLabel OldPasswordLabel;
    private javax.swing.JPasswordField OldPasswordTextField;
    private javax.swing.JLabel OldPasswordWarning;
    private javax.swing.JCheckBox PerformanceBuild;
    private javax.swing.JLabel ReNewPasswordLabel;
    private javax.swing.JPasswordField ReNewPasswordTextField;
    private javax.swing.JLabel ReNewPasswordWarning;
    private javax.swing.JButton SaleButton;
    private javax.swing.JPanel SalePage;
    private javax.swing.JButton Search;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel SearchContent;
    private javax.swing.JPanel SearchContent1;
    private javax.swing.JPanel SearchPage;
    private javax.swing.JScrollPane SearchResult1;
    private javax.swing.JScrollPane SearchResult2;
    private javax.swing.JButton UserButton;
    private javax.swing.JPanel UserPage;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JPanel User_Delete_Page;
    private javax.swing.JPanel User_History_Page;
    private javax.swing.JPanel User_MainSetting_Page;
    private javax.swing.JList<String> User_Setting_List;
    private javax.swing.JLabel User_Setting_Tittle;
    private javax.swing.JLabel UsernamePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

}
