/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import java.lang.String;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JRadioButton;
import org.json.JSONObject;
import pc_builder.TimeHandler;
import pc_builder.UserStorage;
/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {
    private JFrame userHomePage;
    public JSONObject currentUser;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.ButtonGroup();
        Main = new javax.swing.JPanel();
        SignUpPart2 = new javax.swing.JPanel();
        Tittle2 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        NameWarning = new javax.swing.JLabel();
        NameWarning.setVisible(false);
        NameTextField = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        BirthLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        DateBox = new javax.swing.JComboBox<>();
        MonthBox = new javax.swing.JComboBox<>();
        YearBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        GenderButton1 = new javax.swing.JRadioButton();
        GenderButton2 = new javax.swing.JRadioButton();
        GenderButton3 = new javax.swing.JRadioButton();
        SignUpButton2 = new javax.swing.JButton();
        SignUpLable2 = new javax.swing.JLabel();
        NextButton3 = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        LastNameWarning = new javax.swing.JLabel();
        LastNameWarning.setVisible(false);
        RegisterWarning = new javax.swing.JLabel();
        RegisterWarning.setVisible(false);
        AddressWarning = new javax.swing.JLabel();
        AddressWarning.setVisible(false);
        LastNameTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        LoginPart = new javax.swing.JPanel();
        Tittle = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        UserNotFoundWarning = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        SignUpLable = new javax.swing.JLabel();
        SignUpButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SignUpPart1 = new javax.swing.JPanel();
        Tittle1 = new javax.swing.JLabel();
        UsernameLabel1 = new javax.swing.JLabel();
        UsernameTextField1 = new javax.swing.JTextField();
        NextButton1 = new javax.swing.JButton();
        SignUpLable1 = new javax.swing.JLabel();
        SignUpButton1 = new javax.swing.JButton();
        UsernameWarning = new javax.swing.JLabel();
        PasswordLabel2 = new javax.swing.JLabel();
        PasswordTextField1 = new javax.swing.JPasswordField();
        RePasswordTextField = new javax.swing.JPasswordField();
        PasswordLabel3 = new javax.swing.JLabel();
        RePasswordWarning = new javax.swing.JLabel();
        RePasswordWarning.setVisible(false);
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        PasswordWarning = new javax.swing.JLabel();
        EmailWarning = new javax.swing.JLabel();
        EmailWarning.setVisible(false);
        Logo = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        License = new javax.swing.JLabel();
        CompanyLabel = new javax.swing.JLabel();

        Gender.add(GenderButton1);
        Gender.add(GenderButton2);
        Gender.add(GenderButton3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        Main.setEnabled(false);
        Main.setPreferredSize(new java.awt.Dimension(800, 500));
        Main.setLayout(null);

        SignUpPart2.setBackground(new java.awt.Color(254, 254, 254));
        SignUpPart2.setVisible(false);

        Tittle2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Tittle2.setForeground(new java.awt.Color(0, 51, 204));
        Tittle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tittle2.setText("SIGN UP");
        Tittle2.setAlignmentX(0.5F);

        Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Name.setText("Name");

        NameWarning.setForeground(new java.awt.Color(255, 51, 0));
        NameWarning.setText("Password not match");

        NameTextField.setAlignmentX(0.1F);
        NameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameTextFieldFocusLost(evt);
            }
        });

        LastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LastNameLabel.setText("Last Name");

        BirthLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BirthLabel.setText("Birth");

        AddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddressLabel.setText("Address");

        GenderLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GenderLabel.setText("Gender");

        DateBox.setBackground(new java.awt.Color(254, 254, 254));
        DateBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DateBox.setFocusable(false);

        MonthBox.setBackground(new java.awt.Color(254, 254, 254));
        MonthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        MonthBox.setFocusable(false);
        MonthBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthBoxActionPerformed(evt);
            }
        });

        YearBox.setBackground(new java.awt.Color(254, 254, 254));
        YearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1960" }));
        YearBox.setFocusable(false);
        int x = 100; String[] sss = new String[x];
        for (int i=0;i<x;i++) {sss[i] = String.valueOf(1925+i);}
        YearBox.setModel(new javax.swing.DefaultComboBoxModel<String>(sss));

        jLabel2.setText("/");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setText("/");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        GenderButton1.setBackground(new java.awt.Color(255, 255, 255));
        GenderButton1.setSelected(true);
        GenderButton1.setText("Male");
        GenderButton1.setBorder(null);
        GenderButton1.setFocusPainted(false);

        GenderButton2.setBackground(new java.awt.Color(255, 255, 255));
        GenderButton2.setText("Female");
        GenderButton2.setBorder(null);
        GenderButton2.setFocusPainted(false);

        GenderButton3.setBackground(new java.awt.Color(255, 255, 255));
        GenderButton3.setText("Other");
        GenderButton3.setBorder(null);
        GenderButton3.setFocusPainted(false);

        SignUpButton2.setBackground(new java.awt.Color(254, 254, 254));
        SignUpButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SignUpButton2.setForeground(new java.awt.Color(51, 51, 255));
        SignUpButton2.setText("Login");
        SignUpButton2.setBorder(null);
        SignUpButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        SignUpButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButton2ActionPerformed(evt);
            }
        });

        SignUpLable2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SignUpLable2.setText("I already have an account");

        NextButton3.setBackground(new java.awt.Color(102, 102, 255));
        NextButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        NextButton3.setForeground(new java.awt.Color(255, 255, 255));
        NextButton3.setText("Register");
        NextButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NextButton3.setFocusPainted(false);
        NextButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton3ActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(102, 102, 255));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        LastNameWarning.setForeground(new java.awt.Color(255, 51, 0));
        LastNameWarning.setText("Password not match");

        RegisterWarning.setForeground(new java.awt.Color(255, 51, 0));
        RegisterWarning.setText("Please fill all empty box");

        AddressWarning.setForeground(new java.awt.Color(255, 51, 0));
        AddressWarning.setText("Please fill all empty box");

        LastNameTextField.setAlignmentX(0.1F);
        LastNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                LastNameTextFieldFocusLost(evt);
            }
        });

        AddressTextField.setAlignmentX(0.1F);
        AddressTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AddressTextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout SignUpPart2Layout = new javax.swing.GroupLayout(SignUpPart2);
        SignUpPart2.setLayout(SignUpPart2Layout);
        SignUpPart2Layout.setHorizontalGroup(
            SignUpPart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPart2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tittle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(SignUpPart2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(SignUpPart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterWarning)
                    .addGroup(SignUpPart2Layout.createSequentialGroup()
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NextButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Name)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLabel)
                    .addComponent(BirthLabel)
                    .addComponent(AddressLabel)
                    .addComponent(GenderLabel)
                    .addGroup(SignUpPart2Layout.createSequentialGroup()
                        .addGroup(SignUpPart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(GenderButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SignUpPart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SignUpPart2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SignUpPart2Layout.createSequentialGroup()
                                .addComponent(GenderButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GenderButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(SignUpPart2Layout.createSequentialGroup()
                        .addComponent(SignUpLable2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SignUpButton2))
                    .addComponent(NameWarning)
                    .addComponent(LastNameWarning)
                    .addComponent(AddressWarning))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        SignUpPart2Layout.setVerticalGroup(
            SignUpPart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPart2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Tittle2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastNameWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BirthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignUpPart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(SignUpPart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SignUpPart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(YearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(DateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignUpPart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterWarning)
                .addGap(8, 8, 8)
                .addGroup(SignUpPart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignUpPart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignUpLable2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignUpButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Main.add(SignUpPart2);
        SignUpPart2.setBounds(400, 0, 400, 500);

        LoginPart.setBackground(new java.awt.Color(255, 255, 255));
        LoginPart.setEnabled(false);

        Tittle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Tittle.setForeground(new java.awt.Color(0, 51, 204));
        Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tittle.setText("LOGIN");
        Tittle.setAlignmentX(0.5F);

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsernameLabel.setText("Username");

        UsernameTextField.setAlignmentX(0.1F);

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordLabel.setText("Password");

        UserNotFoundWarning.setVisible(false);
        UserNotFoundWarning.setForeground(new java.awt.Color(255, 51, 0));
        UserNotFoundWarning.setText("Username not found or wrong password");

        LoginButton.setBackground(new java.awt.Color(102, 102, 255));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.setFocusPainted(false);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        SignUpLable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SignUpLable.setText("I don't have an account");

        SignUpButton.setBackground(new java.awt.Color(254, 254, 254));
        SignUpButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(51, 51, 255));
        SignUpButton.setText("Sign Up");
        SignUpButton.setBorder(null);
        SignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("🔑");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("👤");

        javax.swing.GroupLayout LoginPartLayout = new javax.swing.GroupLayout(LoginPart);
        LoginPart.setLayout(LoginPartLayout);
        LoginPartLayout.setHorizontalGroup(
            LoginPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tittle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LoginPartLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(LoginPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel)
                    .addGroup(LoginPartLayout.createSequentialGroup()
                        .addComponent(SignUpLable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UserNotFoundWarning)
                    .addComponent(UsernameLabel)
                    .addGroup(LoginPartLayout.createSequentialGroup()
                        .addGroup(LoginPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PasswordTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addComponent(UsernameTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LoginPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        LoginPartLayout.setVerticalGroup(
            LoginPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPartLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(UsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(PasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserNotFoundWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(LoginPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignUpLable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        Main.add(LoginPart);
        LoginPart.setBounds(400, 0, 400, 500);

        SignUpPart1.setBackground(new java.awt.Color(255, 255, 255));
        SignUpPart1.setVisible(false);

        Tittle1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Tittle1.setForeground(new java.awt.Color(0, 51, 204));
        Tittle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tittle1.setText("SIGN UP");
        Tittle1.setAlignmentX(0.5F);

        UsernameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsernameLabel1.setText("Username");

        UsernameTextField1.setAlignmentX(0.1F);
        UsernameTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameTextField1FocusLost(evt);
            }
        });

        NextButton1.setBackground(new java.awt.Color(102, 102, 255));
        NextButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        NextButton1.setForeground(new java.awt.Color(255, 255, 255));
        NextButton1.setText("Next");
        NextButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NextButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton1ActionPerformed(evt);
            }
        });

        SignUpLable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SignUpLable1.setText("I already have an account");

        SignUpButton1.setBackground(new java.awt.Color(254, 254, 254));
        SignUpButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SignUpButton1.setForeground(new java.awt.Color(51, 51, 255));
        SignUpButton1.setText("Login");
        SignUpButton1.setBorder(null);
        SignUpButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        SignUpButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButton1ActionPerformed(evt);
            }
        });

        UsernameWarning.setVisible(false);
        UsernameWarning.setForeground(new java.awt.Color(255, 51, 0));
        UsernameWarning.setText("Username must have atleast 10 characters");

        PasswordLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordLabel2.setText("Password");

        PasswordTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordTextField1FocusLost(evt);
            }
        });

        RePasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                RePasswordTextFieldFocusLost(evt);
            }
        });

        PasswordLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordLabel3.setText("Re-enter Password");

        RePasswordWarning.setForeground(new java.awt.Color(255, 51, 0));
        RePasswordWarning.setText("Password not match");

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailLabel.setText("Email");

        EmailTextField.setAlignmentX(0.1F);

        PasswordWarning.setVisible(false);
        PasswordWarning.setForeground(new java.awt.Color(255, 51, 0));
        PasswordWarning.setText("Username must have atleast 10 characters");

        EmailWarning.setForeground(new java.awt.Color(255, 51, 0));
        EmailWarning.setText("Password not match");

        javax.swing.GroupLayout SignUpPart1Layout = new javax.swing.GroupLayout(SignUpPart1);
        SignUpPart1.setLayout(SignUpPart1Layout);
        SignUpPart1Layout.setHorizontalGroup(
            SignUpPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPart1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tittle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(SignUpPart1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(SignUpPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailWarning)
                    .addComponent(NextButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RePasswordWarning)
                    .addGroup(SignUpPart1Layout.createSequentialGroup()
                        .addComponent(SignUpLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SignUpButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UsernameWarning)
                    .addComponent(EmailLabel)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel1)
                    .addComponent(UsernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel2)
                    .addComponent(PasswordTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RePasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel3)
                    .addComponent(PasswordWarning))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        SignUpPart1Layout.setVerticalGroup(
            SignUpPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPart1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Tittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UsernameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(UsernameWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RePasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(RePasswordWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NextButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(SignUpPart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignUpLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignUpButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        Main.add(SignUpPart1);
        SignUpPart1.setBounds(400, 0, 400, 500);

        Logo.setBackground(new java.awt.Color(153, 153, 255));
        Logo.setMinimumSize(new java.awt.Dimension(400, 500));

        Icon.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Icon.setForeground(new java.awt.Color(255, 255, 255));
        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icon.png"))); // NOI18N
        Icon.setText("PC BUILDER");

        Description.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Description.setForeground(new java.awt.Color(255, 255, 255));
        Description.setText("Build PC with ease");

        License.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        License.setForeground(new java.awt.Color(255, 255, 255));
        License.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        License.setText("copyright © Eitech All right reserved");

        CompanyLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CompanyLabel.setForeground(new java.awt.Color(255, 255, 255));
        CompanyLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CompanyLabel.setText("Eitech");

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Description)
                    .addComponent(Icon, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(License, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CompanyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(CompanyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(License)
                .addGap(50, 50, 50))
        );

        Main.add(Logo);
        Logo.setBounds(0, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("LOGIN");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
        LoginPart.setVisible(false);
        SignUpPart1.setVisible(true);
        SignUpPart2.setVisible(false);
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void SignUpButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButton1ActionPerformed
        // TODO add your handling code here:
        LoginPart.setVisible(true);
        SignUpPart1.setVisible(false);
        SignUpPart2.setVisible(false);
    }//GEN-LAST:event_SignUpButton1ActionPerformed

    private void SignUpButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButton2ActionPerformed
        // TODO add your handling code here:
        LoginPart.setVisible(true);
        SignUpPart1.setVisible(false);
        SignUpPart2.setVisible(false);
    }//GEN-LAST:event_SignUpButton2ActionPerformed

    private void NextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton1ActionPerformed
        // TODO add your handling code here:
        SignUpPart1.setVisible(false);
        SignUpPart2.setVisible(true);
    }//GEN-LAST:event_NextButton1ActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        SignUpPart1.setVisible(true);
        SignUpPart2.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void NameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameTextFieldFocusLost
        // TODO add your handling code here:
        NameWarning.setVisible(false);
        String content = NameTextField.getText();
        if (content.length()==0) {
            NameWarning.setText("This container must have information");
            NameWarning.setVisible(true);
        }
    }//GEN-LAST:event_NameTextFieldFocusLost

    private void UsernameTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameTextField1FocusLost
        // TODO add your handling code here:
        UsernameWarning.setVisible(false);
        String content = UsernameTextField1.getText();
        if (content.length()==0) {
            UsernameWarning.setText("Username must have atleast 10 characters");
            UsernameWarning.setVisible(true);
        }
    }//GEN-LAST:event_UsernameTextField1FocusLost

    private void RePasswordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RePasswordTextFieldFocusLost
        // TODO add your handling code here:
        String firstPass = String.copyValueOf(PasswordTextField1.getPassword());
        String secondPass = String.copyValueOf(RePasswordTextField.getPassword());
        RePasswordWarning.setVisible(false);
        if (secondPass.compareTo(firstPass)!=0) {
            RePasswordWarning.setText("Password not match");
            RePasswordWarning.setVisible(true);
        }
    }//GEN-LAST:event_RePasswordTextFieldFocusLost

    private void MonthBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthBoxActionPerformed
        // TODO add your handling code here:
        String[] s = new String[] {"31","29","31","30","31","30","31","31","30","31","30","31"};
        int day = Integer.parseInt(s[MonthBox.getSelectedIndex()]);
        String[] ss = new String[day];
        for (int i=0;i<day;i++) {
            ss[i] = String.valueOf(1+i);
        }
        DateBox.setModel(new javax.swing.DefaultComboBoxModel<String>(ss));
    }//GEN-LAST:event_MonthBoxActionPerformed

    private void PasswordTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordTextField1FocusLost
        // TODO add your handling code here:
        PasswordWarning.setVisible(false);
        String content = String.copyValueOf(PasswordTextField1.getPassword());
        if (content.length()==0) {
            PasswordWarning.setText("Password cannot leave blank");
            PasswordWarning.setVisible(true);
        }
    }//GEN-LAST:event_PasswordTextField1FocusLost

    private void reset() {
        UsernameTextField.setText("");
        PasswordTextField.setText("");
        PasswordTextField1.setText("");
        RePasswordTextField.setText("");
        NameTextField.setText("");
        LastNameTextField.setText("");
        UsernameTextField1.setText("");
        EmailTextField.setText("");
        LastNameTextField.setText("");
        AddressTextField.setText("");
        
        NameWarning.setVisible(false);
        LastNameWarning.setVisible(false);
        UsernameWarning.setVisible(false);
        PasswordWarning.setVisible(false);
        RePasswordWarning.setVisible(false);
        EmailWarning.setVisible(false);
        AddressWarning.setVisible(false);
        
        LoginPart.setVisible(true);
        SignUpPart1.setVisible(false);
        SignUpPart2.setVisible(false);
    }
    
    private boolean checkForWarning() {
        if (NameWarning.isVisible()) return false;
        if (LastNameWarning.isVisible()) return false;
        if (UsernameWarning.isVisible()) return false;
        if (PasswordWarning.isVisible()) return false;
        if (RePasswordWarning.isVisible()) return false;
        if (EmailWarning.isVisible()) return false;
        if (AddressWarning.isVisible()) return false;
        return true;
    }
    
    private void NextButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton3ActionPerformed
        // TODO add your handling code here:
        RegisterWarning.setVisible(false);
        if (checkForWarning()) {
            String username = UsernameTextField1.getText();
            String password = String.copyValueOf(PasswordTextField1.getPassword());
            String email = EmailTextField.getText();
            String name = NameTextField.getText();
            String lastName = LastNameTextField.getText();
            String gender = null;
            if (GenderButton1.isSelected()) gender = GenderButton1.getText();
            if (GenderButton2.isSelected()) gender = GenderButton2.getText();
            if (GenderButton3.isSelected()) gender = GenderButton3.getText();
            JSONObject birth = new JSONObject();
            birth.put("day", Integer.parseInt(DateBox.getSelectedItem().toString()));
            birth.put("month", Integer.parseInt(MonthBox.getSelectedItem().toString()));
            birth.put("year", Integer.parseInt(YearBox.getSelectedItem().toString()));
            String address = LastNameTextField.getText();
            
            JSONObject newUser = UserStorage.Sample();
            newUser.put("username", username);
            newUser.put("password", password);
            newUser.put("email", email);
            newUser.put("name", name);
            newUser.put("last_Name", lastName);
            newUser.put("birth", birth);
            newUser.put("gender", gender);
            newUser.put("address", address);
            newUser.put("admin", false);
            newUser.put("balance", 0);
            JSONObject history = new JSONObject();
            
            JSONObject today = new JSONObject();
            today.put("time", TimeHandler.getCurrentDay());
            today.put("action", "User register");
            
            history.put("0", today);
            newUser.put("history", history);
            UserStorage.addItem(newUser);
            reset();
        } else {
            RegisterWarning.setVisible(true);
        }
    }//GEN-LAST:event_NextButton3ActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        String username = UsernameTextField.getText();
        String password = String.copyValueOf(PasswordTextField.getPassword());
        UserNotFoundWarning.setVisible(false);
        JSONObject user = UserStorage.getItem(username);
        if (user != null) {
            try {
                if (UserStorage.verifyPassword(user.getString("password"), password)) {
                    System.out.println("Login complete!!!, Hello %s!".formatted(user.get("username")));
                    currentUser = user;
                    if ((boolean)user.get("admin")) {
                        userHomePage = new Admin(this);
                        userHomePage.setLocationRelativeTo(null);
                        userHomePage.setVisible(true);
                    } else {
                        userHomePage = new Home(this);
                        userHomePage.setLocationRelativeTo(null);
                        userHomePage.setVisible(true);
                    }
                    this.hide();
                } else {
                    System.out.println("Wrong password!!!");
                    UserNotFoundWarning.setVisible(true);
                }
            } catch (NoSuchAlgorithmException ex) {
                System.out.println("Error can't found user!");
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //System.out.println(UserStorage.loadItems().toString());
            System.out.println("User not exist!!!");
            UserNotFoundWarning.setVisible(true);
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LastNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastNameTextFieldFocusLost
        // TODO add your handling code here:
        LastNameWarning.setVisible(false);
        String content = LastNameTextField.getText();
        if (content.length()==0) {
            LastNameWarning.setText("This container must have information");
            LastNameWarning.setVisible(true);
        }
    }//GEN-LAST:event_LastNameTextFieldFocusLost

    private void AddressTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AddressTextFieldFocusLost
        // TODO add your handling code here:
        AddressWarning.setVisible(false);
        String content = AddressTextField.getText();
        if (content.length()==0) {
            AddressWarning.setText("This container must have information");
            AddressWarning.setVisible(true);
        }
    }//GEN-LAST:event_AddressTextFieldFocusLost

    public void close() {
        userHomePage.dispose();
        userHomePage = null;
        reset();
        this.show();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public JRadioButton getGenderButton1() {
        return GenderButton1;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JLabel AddressWarning;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BirthLabel;
    private javax.swing.JLabel CompanyLabel;
    private javax.swing.JComboBox<String> DateBox;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel EmailWarning;
    private javax.swing.ButtonGroup Gender;
    private javax.swing.JRadioButton GenderButton1;
    private javax.swing.JRadioButton GenderButton2;
    private javax.swing.JRadioButton GenderButton3;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel LastNameWarning;
    private javax.swing.JLabel License;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginPart;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel Main;
    private javax.swing.JComboBox<String> MonthBox;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel NameWarning;
    private javax.swing.JButton NextButton1;
    private javax.swing.JButton NextButton3;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordLabel2;
    private javax.swing.JLabel PasswordLabel3;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JPasswordField PasswordTextField1;
    private javax.swing.JLabel PasswordWarning;
    private javax.swing.JPasswordField RePasswordTextField;
    private javax.swing.JLabel RePasswordWarning;
    private javax.swing.JLabel RegisterWarning;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JButton SignUpButton1;
    private javax.swing.JButton SignUpButton2;
    private javax.swing.JLabel SignUpLable;
    private javax.swing.JLabel SignUpLable1;
    private javax.swing.JLabel SignUpLable2;
    private javax.swing.JPanel SignUpPart1;
    private javax.swing.JPanel SignUpPart2;
    private javax.swing.JLabel Tittle;
    private javax.swing.JLabel Tittle1;
    private javax.swing.JLabel Tittle2;
    private javax.swing.JLabel UserNotFoundWarning;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel UsernameLabel1;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JTextField UsernameTextField1;
    private javax.swing.JLabel UsernameWarning;
    private javax.swing.JComboBox<String> YearBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
