/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Base64;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.json.JSONObject;

/**
 *
 * @author Admin
 */
public class SearchItem extends javax.swing.JPanel {
    private JSONObject device;
    /**
     * Creates new form SearchItem
     */
    public static BufferedImage getBufferedImageFromJson(JSONObject jsonObject, String key) throws IOException {
        if (!jsonObject.has(key)) {
            throw new IllegalArgumentException("Key not found in JSONObject: " + key);
        }

        String base64Image = jsonObject.getString(key); // Get string Base64 from JSON
        byte[] imageBytes = Base64.getDecoder().decode(base64Image); // Decode Base64

        // Change into BufferedImage
        try (ByteArrayInputStream bis = new ByteArrayInputStream(imageBytes)) {
            return ImageIO.read(bis);
        }
    }
    
    public SearchItem(JSONObject device) {
        this.device = device;
        this.setLayout(null);
        
        initComponents();
        
        DeviceName.setText(device.getString("name"));
        DeviceType.setText(device.getString("type")+"  |  "+device.getString("brand"));
        DeviceCost.setText("$"+device.get("price").toString());
        
        try {
            BufferedImage originalImage = getBufferedImageFromJson(device, "icon");
            BufferedImage resizedImage = new BufferedImage(50, 50, originalImage.getType());
            Graphics2D g2d = resizedImage.createGraphics();
            g2d.drawImage(originalImage, 0, 0, 50, 50, null);
            g2d.dispose();
            ImageIcon originalIcon = new ImageIcon(resizedImage);

            Image scaledImage = originalIcon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            JLabel imageLabel = new JLabel(scaledIcon);
            imageLabel.setBounds(0, 0, 50, 50);
            
            Icon.add(imageLabel);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon = new javax.swing.JPanel();
        DeviceName = new javax.swing.JButton();
        DeviceType = new javax.swing.JLabel();
        DeviceCost = new javax.swing.JLabel();

        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(765, 62));
        setPreferredSize(new java.awt.Dimension(877, 62));

        Icon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout IconLayout = new javax.swing.GroupLayout(Icon);
        Icon.setLayout(IconLayout);
        IconLayout.setHorizontalGroup(
            IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        IconLayout.setVerticalGroup(
            IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        DeviceName.setBackground(new java.awt.Color(242, 242, 242));
        DeviceName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DeviceName.setForeground(new java.awt.Color(0, 51, 204));
        DeviceName.setText("Device Name");
        DeviceName.setBorder(null);
        DeviceName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DeviceName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        DeviceType.setForeground(new java.awt.Color(102, 0, 51));
        DeviceType.setText("Some tittle");

        DeviceCost.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeviceCost.setForeground(new java.awt.Color(0, 204, 51));
        DeviceCost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DeviceCost.setText("$10-$200");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeviceType, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addComponent(DeviceCost, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DeviceName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeviceName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeviceType)
                            .addComponent(DeviceCost)))
                    .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DeviceCost;
    private javax.swing.JButton DeviceName;
    private javax.swing.JLabel DeviceType;
    private javax.swing.JPanel Icon;
    // End of variables declaration//GEN-END:variables
}
