/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Base64;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.json.JSONObject;
import pc_builder.Device;

/**
 *
 * @author Admin
 */
public class SearchItem extends javax.swing.JPanel {
    private Device device;
    private Home parent;
    /**
     * Creates new form SearchItem
     */
    public static BufferedImage getBufferedImageFromJson(String base64Image) throws IOException {// Get string Base64 from JSON
        byte[] imageBytes = Base64.getDecoder().decode(base64Image); // Decode Base64

        // Change into BufferedImage
        try (ByteArrayInputStream bis = new ByteArrayInputStream(imageBytes)) {
            return ImageIO.read(bis);
        }
    }
    
    public SearchItem(Home parent, String device) {
        this.device = Device.getDevice(device);
        this.parent = parent;
        this.setLayout(null);
        
        initComponents();
        
        DeviceName.setText(this.device.getName());
        DeviceType.setText(this.device.getType()+"  |  "+this.device.getBrand());
        DeviceCost.setText("$%.2f".formatted(this.device.getPrice()));
        if (this.device.isForSale()) {
            DeviceDiscount.setText("$%.2f".formatted(this.device.getPrice()-this.device.truePrice));
            DeviceCost.setText("$%.2f".formatted(this.device.truePrice));
        }
        try {
            BufferedImage originalImage = getBufferedImageFromJson(this.device.getIcon());
            BufferedImage resizedImage = new BufferedImage(50, 50, originalImage.getType());
            Graphics2D g2d = resizedImage.createGraphics();
            g2d.drawImage(originalImage, 0, 0, 50, 50, null);
            g2d.dispose();
            ImageIcon originalIcon = new ImageIcon(resizedImage);

            Image scaledImage = originalIcon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            JLabel imageLabel = new JLabel(scaledIcon);
            imageLabel.setBounds(0, 0, 50, 50);
            
            Icon.add(imageLabel);
        } catch (Exception e) {
        }
    }

    public void purchase() {
        parent.purchase(this.device.getId());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon = new javax.swing.JPanel();
        DeviceName = new javax.swing.JButton();
        DeviceType = new javax.swing.JLabel();
        DeviceDiscount = new javax.swing.JLabel();
        DeviceCost = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(765, 70));
        setMinimumSize(new java.awt.Dimension(765, 0));
        setPreferredSize(new java.awt.Dimension(877, 75));
        setLayout(null);

        Icon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Icon.setMaximumSize(new java.awt.Dimension(50, 50));
        Icon.setMinimumSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout IconLayout = new javax.swing.GroupLayout(Icon);
        Icon.setLayout(IconLayout);
        IconLayout.setHorizontalGroup(
            IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        IconLayout.setVerticalGroup(
            IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        add(Icon);
        Icon.setBounds(21, 9, 50, 50);

        DeviceName.setBackground(new java.awt.Color(242, 242, 242));
        DeviceName.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        DeviceName.setForeground(new java.awt.Color(0, 51, 204));
        DeviceName.setText("Device Name");
        DeviceName.setBorder(null);
        DeviceName.setContentAreaFilled(false);
        DeviceName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeviceName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DeviceName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        DeviceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeviceNameActionPerformed(evt);
            }
        });
        add(DeviceName);
        DeviceName.setBounds(77, 9, 573, 24);

        DeviceType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeviceType.setForeground(new java.awt.Color(102, 0, 51));
        DeviceType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DeviceType.setText("Some tittle");
        DeviceType.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(DeviceType);
        DeviceType.setBounds(77, 39, 461, 20);

        DeviceDiscount.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        DeviceDiscount.setForeground(new java.awt.Color(204, 102, 0));
        DeviceDiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(DeviceDiscount);
        DeviceDiscount.setBounds(630, 9, 100, 30);

        DeviceCost.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        DeviceCost.setForeground(new java.awt.Color(0, 204, 51));
        DeviceCost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DeviceCost.setText("$10-$200");
        DeviceCost.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(DeviceCost);
        DeviceCost.setBounds(600, 39, 131, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void DeviceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeviceNameActionPerformed
        // TODO add your handling code here:
        DeviceInformation newInfo = new DeviceInformation(parent, device.getId());
        newInfo.setLocationRelativeTo(null);
        newInfo.setVisible(true);
    }//GEN-LAST:event_DeviceNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DeviceCost;
    private javax.swing.JLabel DeviceDiscount;
    private javax.swing.JButton DeviceName;
    private javax.swing.JLabel DeviceType;
    private javax.swing.JPanel Icon;
    // End of variables declaration//GEN-END:variables
}
